name:                ReversePolishCalculator
version:             0.1.0.0
license:             BSD3
author:              Joshua Billson
maintainer:          jmbillson@outlook.com
copyright:           2021 Joshua Billson

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on GitHub at <https://github.com/Github username here/ReversePolishCalculator#readme>

dependencies:
- base >= 4.7 && < 5
- regex-compat

library:
  source-dirs: src

executables:
  ReversePolishCalculator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ReversePolishCalculator

tests:
  ReversePolishCalculator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ReversePolishCalculator
